FROM node:18 AS buildphase

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . ./

# Set API URL for React inside Docker
ARG REACT_APP_API_URL=http://api-gateway:8086
ENV REACT_APP_API_URL=${REACT_APP_API_URL}

RUN npm run build

FROM nginx:latest
RUN rm -rf /usr/share/nginx/html/*

COPY --from=buildphase /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

