version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: rohan
      MYSQL_PASSWORD: Rohan@445
    ports:
      - "3307:3306"

    volumes:
      - mysql_datavolume:/var/lib/mysql

    networks:
      - ecommerce-network
   
  user-service:
    build: ./user-service
    container_name: user-service-container
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql-db
      DB_USER: rohan
      DB_PASSWORD: Rohan@445
      DB_NAME: ecommerce
    
    networks:
      - ecommerce-network

  auth-service:
    build: ./auth-service
    container_name: auth-service-container
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql-db
      DB_USER: rohan
      DB_PASSWORD: Rohan@445
      DB_NAME: ecommerce

    networks:
      - ecommerce-network
  
  product-service:
    build: ./product-service
    container_name: product-service-container
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql-db
      DB_USER: rohan
      DB_PASSWORD: Rohan@445
      DB_NAME: ecommerce

    networks:
      - ecommerce-network 
   
  order-service:
    build: ./order-service
    container_name: order-service-container
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql-db
      DB_USER: rohan
      DB_PASSWORD: Rohan@445
      DB_NAME: ecommerce

    networks:
      - ecommerce-network


  cart-service:
    build: ./cart-service
    container_name: cart-service-container
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql-db
      DB_USER: rohan
      DB_PASSWORD: Rohan@445
      DB_NAME: ecommerce

    networks:
      - ecommerce-network

  frontend:
    build: ./frontend
    container_name: frontend-container
    environment:
      - REACT_APP_API_URL=http://api-gateway:8086
    depends_on:
      - api-gateway
    networks:
      - ecommerce-network
    ports:
      - "3000:80"


  api-gateway:
    build: ./api-gateway
    container_name: api-gateway-container
    depends_on:
      - product-service
      - user-service
      - auth-service
      - cart-service
      - order-service
      - mysql
    environment:
      DB_HOST: mysql-db
      DB_USER: rohan
      DB_PASSWORD: Rohan@445
      DB_NAME: ecommerce

    networks:
      - ecommerce-network

    ports:
      - "8086:8086"


networks:
  ecommerce-network:
        

volumes:
  mysql_datavolume:
